# Generated by Django 2.2 on 2021-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookitem',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='podcastitem',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='duration',
            field=models.DurationField(),
        ),
    ]
