# Generated by Django 2.2 on 2021-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook_api', '0004_auto_20210516_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songitem',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
