# Generated by Django 2.2 on 2021-05-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook_api', '0005_auto_20210516_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobookitem',
            old_name='name',
            new_name='title',
        ),
    ]
