# Generated by Django 2.2 on 2021-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook_api', '0006_auto_20210516_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='songitem',
            name='songfile',
            field=models.FileField(default=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='audiobookitem',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audiobookitem',
            name='narrator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audiobookitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastitem',
            name='host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='podcastitem',
            name='participants',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
